language: go
go:
  - 1.5
  - 1.6
  - 1.7

sudo: false
dist: trusty

install:
  - go get -v -t ./...
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

script:
  - go test -v ./store -covermode=count -coverprofile=./store/.coverprofile
  - $HOME/gopath/bin/gover
  - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN

branches:
  only:
    - master

env:
  global:
    secure: EqN5YuHXRN5lTu6li2XEWmvcUAg2yZs6Ozvi3zP7icYnt5udI6L8bAxuSpgs1OROUQvF/qQc7TG6AXD22uzmetTXgFvCq1MuXv51Zei6W2xIJlrvRzmXTrRdoFbUyaySncApGrp4TweQ5/amN0aWsXQ57OwACYhGtJgPtLtMxrTFLqozTMZE4bx+HE8TknHbKHHAs5yUv4O6hE+yclFUiarv4tyXeVMcIfjsOS8sk14GZblBmYvYdYC0IVf6euKNEIoFOmnQhe6aGJzM9IQy0VErvAaT7X149+zX+S9X6mAK2iQCIb+V6MKtEAg7ZjYVODkAy2kOgnDlFoWmK8v7eTRHcL4LDHIc00JZjCkLuW8yolr+XuCAbrhSFPpxX44upnadbOHiK6EHeBeoELU9LKXkwgcELsjdPojZr9S3huUbYkAujgRYmm/hvJDLhDm7JRWDkU6xSOLnizIiqlbxK6A3XFrHoiTfYt57uMl2ZXtRwWxaTei0W5WSNMDTFtytWLuqYyj6tw3ug/VrxU80xyHdZXg0MyBYotd6iOs07CBMPeht+CvMQejAfDi3lQJuLLjPBVRjHKCqr1C2uUBGwyNKYrRAWQzV+4wcdAi/TdVS2c8P+21Cef9aNtBh4g5wizz88ixFtv3DELccOBsgNp38jCGzdAg7lwvhHHJhalM=
